version: 2

integration_steps:


  install-docker-compose: &install-docker-compose
    run:
      name: Install Docker Compose
      command: |
        pip install docker-compose

  run-env: &run-env
    run:
      name: Get the environment up and running with Docker Compose
      command: |
        cd tests/integration && make && make run

  run-tests: &run-tests
    run:
      name: Run integration tests
      command: |
        cd tests/integration && make test

jobs:
  py3_integration_tests:
    machine: true
    working_directory: /home/circleci/project
    steps:
      - run:
          name: Set up Python 3.8
          command: |
             pyenv install 3.8 || true
             pyenv global 3.8

      - checkout
      - *install-docker-compose
      - *run-env
      - *run-tests

  unit_tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: tox -e py38

  release:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Release to PyPI
          command: tox -e release

workflows:
  version: 2

  ci:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /^v.*/
      - unit_tests_311:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - unit_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
